name: Gradle test for pull request

on:
  pull_request:
    branches: [ freddie-noel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        id: build-with-gradle
        run: ./gradlew build
        continue-on-error: true
      - name: Show info When Build Failed
        if: steps.build-with-gradle.outcome == 'failure'
        run: ./gradlew build -i
